apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - name: dynamodb-container
        image: amazon/dynamodb-local
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-service
spec:
  selector:
    app: dynamodb
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000