apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - name: dynamodb-container
        image: amazon/dynamodb-local
        command:
            - "java"
        args:
          - "-jar"
          - "DynamoDBLocal.jar"
          - "-sharedDb"
          - "-dbPath"
          - "/home/dynamodblocal/data"
        volumeMounts:
          - mountPath: /home/dynamodblocal/data
            name: dynamo-pv-storage
  volumeClaimTemplates:
    - metadata:
        name: dynamo-pv-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-service
spec:
  selector:
    app: dynamodb
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000