apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
      - ./k8s/dynamo/*
      - ./k8s/postgres/*
  kubeContext: minikube
build:
  local:
    push: false
  artifacts:
    - image: app-image
      context: app
      docker:
        dockerfile: docker/Dockerfile.dev
      sync:
        infer:
          - "src/**/*.py"