apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-conf
  labels:
    app: sample-db
data:
  POSTGRES_DB: sample-db
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
data:
  password: cG9zdGdyZXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-db
  template:
    metadata:
      labels:
        app: sample-db
    spec:
      volumes:
        - name: sample-db-pv
          persistentVolumeClaim:
            claimName: sample-db-pv-claim
      containers:
        - name: postgres-container
          image: postgres:13-alpine
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: sample-db-pv
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-conf
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: sample-db-service
spec:
  selector:
    app: sample-db
  ports:
  - protocol: "TCP"
    port: 5433
    targetPort: 5432
  type: LoadBalancer